const ActionTypes = {
  SET_USERS: 'SET_USERS',
  SET_WORK_MESSAGE: 'SET_WORK_MESSAGE',
  SET_FLOOD_MESSAGE: 'SET_FLOOD_MESSAGE',
  UPDATE_WORK_MESSAGE: 'UPDATE_WORK_MESSAGE',
  UPDATE_FLOOD_MESSAGE: 'UPDATE_FLOOD_MESSAGE',
  DELETE_WORK_MESSAGE: 'DELETE_WORK_MESSAGE',
  DELETE_FLOOD_MESSAGE: 'DELETE_FLOOD_MESSAGE',
};

export default ActionTypes;
